export const ADD_TO_CART = "ADD_TO_CART"
export const INCREASE_CART_COUNT = "INCREASE_CART_COUNT"
export const DECREASE_CART_COUNT = "DECREASE_CART_COUNT"
export const REMOVE_TO_CART = "REMOVE_TO_CART"


export const EMPTY_CART = "EMPTY_CART"
export const PRODUCT_LIST = "PRODUCT_LIST"
export const PRODUCT_SET = "PRODUCT_SET"


export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST"
export const REMOVE_TO_WISHLIST = "REMOVE_TO_WISHLIST"

